version: 2
jobs:
  build:
    working_directory: ~/rack_app
    docker:
      - image: ruby:2.7.1-alpine
    environment:
      - RACK_ENV: test
    steps:
      # Install dependencies
      - run: apk update && apk upgrade && apk add g++ make musl-dev gzip tar git

      - checkout

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(tail Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec

      # Upload rspec results to CircleCI
      - store_test_results:
          path: /tmp/test-results

      # Run rubocop
      - run: bundle exec rubocop -DES
